/**
 * Bestseller cards data — migrated exactly from index.html
 * 12 bestseller cards with identical content, icons, links, and class names
 */
export const bestsellerCards = [
  {
    id: "sparkling-candles",
    slug: "sparkling-candles",
    cssClass: "card-sparkling-candles",
    iconClass: "icon-sparkling-candles",
    icon: "fa-solid fa-wand-magic-sparkles",
    image: "bestsellers1.png",
    alt: "Sparkling Candles",
    title: "Sparkling Candles",
    description: "Light up the celebration with sparkle",
    link: "/bestseller/sparkling-candles",
    btnClass: "link-sparkling-candles",
  },
  {
    id: "metallic-balloons",
    slug: "metallic-balloons",
    cssClass: "card-metallic-balloons",
    iconClass: "icon-metallic-balloons",
    icon: "fa-solid fa-parachute-box",
    image: "bestsellers2.png",
    alt: "Metallic Balloons",
    title: "Metallic Balloons",
    description: "Shiny balloons for a premium look",
    link: "/bestseller/metallic-balloons",
    btnClass: "link-metallic-balloons",
  },
  {
    id: "cake-dolls",
    slug: "cake-dolls",
    cssClass: "card-cake-dolls",
    iconClass: "icon-cake-dolls",
    icon: "fa-solid fa-child",
    image: "bestsellers3.png",
    alt: "Cake Dolls",
    title: "Cake Dolls",
    description: "Adorable dolls to brighten your cake",
    link: "/bestseller/cake-dolls",
    btnClass: "link-cake-dolls",
  },
  {
    id: "golden-no-candles",
    slug: "golden-no-candles",
    cssClass: "card-golden-candles",
    iconClass: "icon-golden-candles",
    icon: "fa-solid fa-1",
    image: "bestsellers4.png",
    alt: "Golden No Candles",
    title: "Golden No Candles",
    description: "Golden number candles for every age",
    link: "/bestseller/golden-no-candles",
    btnClass: "link-golden-candles",
  },
  {
    id: "balloon-pump",
    slug: "balloon-pump",
    cssClass: "card-balloon-pump",
    iconClass: "icon-balloon-pump",
    icon: "fa-solid fa-pump-medical",
    image: "bestsellers5.png",
    alt: "Balloon Pump",
    title: "Balloon Pump",
    description: "Easy & quick inflation every time",
    link: "/bestseller/balloon-pump",
    btnClass: "link-balloon-pump",
  },
  {
    id: "3d-butterfly",
    slug: "3d-butterfly",
    cssClass: "card-butterfly",
    iconClass: "icon-butterfly",
    icon: "fa-solid fa-dove",
    image: "bestsellers6.png",
    alt: "3D Butterfly",
    title: "3D Butterfly",
    description: "Elegant 3D butterflies for décor",
    link: "/bestseller/3d-butterfly",
    btnClass: "link-butterfly",
  },
  {
    id: "snow-spray",
    slug: "snow-spray",
    cssClass: "card-snow-spray",
    iconClass: "icon-snow-spray",
    icon: "fa-solid fa-snowflake",
    image: "bestsellers7.png",
    alt: "Snow Spray",
    title: "Snow Spray",
    description: "Add a magical snow effect to your party",
    link: "/bestseller/snow-spray",
    btnClass: "link-snow-spray",
  },
  {
    id: "crazy-ribbon",
    slug: "crazy-ribbon",
    cssClass: "card-crazy-ribbon",
    iconClass: "icon-crazy-ribbon",
    icon: "fa-solid fa-ribbon",
    image: "bestsellers8.png",
    alt: "Crazy Ribbon",
    title: "Crazy Ribbon",
    description: "Add a fun twist to your decorations",
    link: "/bestseller/crazy-ribbon",
    btnClass: "link-crazy-ribbon",
  },
  {
    id: "party-poppers",
    slug: "party-poppers",
    cssClass: "card-party-poppers",
    iconClass: "icon-party-poppers",
    icon: "fa-solid fa-wand-magic-sparkles",
    image: "bestsellers9.png",
    alt: "Party Poppers",
    title: "Party Poppers",
    description: "Make your party pop with excitement",
    link: "/bestseller/party-poppers",
    btnClass: "link-party-poppers",
  },
  {
    id: "birthday-caps",
    slug: "birthday-caps",
    cssClass: "card-birthday-caps",
    iconClass: "icon-birthday-caps",
    icon: "fa-solid fa-hat-wizard",
    image: "bestsellers10.png",
    alt: "Birthday Caps",
    title: "Birthday Caps",
    description: "Fun and stylish caps for the birthday star",
    link: "/bestseller/birthday-caps",
    btnClass: "link-birthday-caps",
  },
  {
    id: "theme-cake-toppers",
    slug: "theme-cake-toppers",
    cssClass: "card-theme-toppers",
    iconClass: "icon-theme-toppers",
    icon: "fa-solid fa-star",
    image: "bestsellers11.png",
    alt: "Theme Cake Toppers",
    title: "Theme Cake Toppers",
    description: "Special toppers for every theme & occasion",
    link: "/bestseller/theme-cake-toppers",
    btnClass: "link-theme-toppers",
  },
  {
    id: "many-more",
    slug: "many-more",
    cssClass: "card-bestsellers-manymore",
    iconClass: "icon-bestsellers-manymore",
    icon: "fa-solid fa-gift",
    image: "bestsellers12.png",
    alt: "Many More",
    title: "Many More",
    description: "Explore more exciting party essentials",
    link: "/bestseller/many-more",
    btnClass: "link-bestsellers-manymore",
  },
];
