/**
 * Category cards data — migrated exactly from index.html
 * 12 category cards with identical content, icons, links, and class names
 */
export const categoryCards = [
  {
    id: "balloons",
    cssClass: "card-balloons",
    iconClass: "icon-balloons",
    icon: "fa-solid fa-parachute-box",
    image: "cardballoons.png",
    alt: "Balloons",
    title: "Balloons",
    description: "Colorful balloons for every celebration",
    link: "/products?category=balloons",
    btnClass: "link-balloons",
  },
  {
    id: "birthday-caps",
    cssClass: "card-caps",
    iconClass: "icon-caps",
    icon: "fa-solid fa-hat-wizard",
    image: "cardcaps.png",
    alt: "Birthday Caps",
    title: "Birthday Caps",
    description: "Fun and stylish caps for the birthday star",
    link: "/products?category=birthday-caps",
    btnClass: "link-caps",
  },
  {
    id: "party-poppers",
    cssClass: "card-poppers",
    iconClass: "icon-poppers",
    icon: "fa-solid fa-wand-magic-sparkles",
    image: "cardpoppers.png",
    alt: "Party Poppers",
    title: "Party Poppers",
    description: "Make your party pop with excitement",
    link: "/products?category=party-poppers",
    btnClass: "link-poppers",
  },
  {
    id: "candles",
    cssClass: "card-candles",
    iconClass: "icon-candles",
    icon: "fa-solid fa-cake-candles",
    image: "cardcandles.png",
    alt: "Cake Candles",
    title: "Cake Candles",
    description: "Brighten the cake and make wishes come true",
    link: "/products?category=candles",
    btnClass: "link-candles",
  },
  {
    id: "sashes",
    cssClass: "card-sashes",
    iconClass: "icon-sashes",
    icon: "fa-solid fa-ribbon",
    image: "cardsashes.png",
    alt: "Sashes",
    title: "Sashes",
    description: "Stylish sashes for the birthday star",
    link: "/products?category=sashes",
    btnClass: "link-sashes",
  },
  {
    id: "banners",
    cssClass: "card-banners",
    iconClass: "icon-banners",
    icon: "fa-solid fa-flag",
    image: "card banner.png",
    alt: "Paper Banners",
    title: "Paper Banners",
    description: "Decorate in style with birthday banners",
    link: "/products?category=banners",
    btnClass: "link-banners",
  },
  {
    id: "cake-knives",
    cssClass: "card-knives",
    iconClass: "icon-knives",
    icon: "fa-solid fa-utensils",
    image: "card knives.png",
    alt: "Cake Cutting Knives",
    title: "Cake Cutting Knives",
    description: "Perfect knives for a perfect cake moment",
    link: "/products?category=cake-knives",
    btnClass: "link-knives",
  },
  {
    id: "tiara",
    cssClass: "card-tiara",
    iconClass: "icon-tiara",
    icon: "fa-solid fa-gem",
    image: "cardtiara.png",
    alt: "Birthday Tiara",
    title: "Birthday Tiara",
    description: "Shine like a star on your special day",
    link: "/products?category=tiara",
    btnClass: "link-tiara",
  },
  {
    id: "crowns",
    cssClass: "card-crowns",
    iconClass: "icon-crowns",
    icon: "fa-solid fa-crown",
    image: "cardcrowns.png",
    alt: "Birthday Crowns",
    title: "Birthday Crowns",
    description: "Royal crowns for our birthday kings & queens",
    link: "/products?category=crowns",
    btnClass: "link-crowns",
  },
  {
    id: "toppers",
    cssClass: "card-toppers",
    iconClass: "icon-toppers",
    icon: "fa-solid fa-star",
    image: "cardtoppers.png",
    alt: "Cake Toppers",
    title: "Cake Toppers",
    description: "Top your cakes with love and style",
    link: "/products?category=toppers",
    btnClass: "link-toppers",
  },
  {
    id: "combos",
    cssClass: "card-combos",
    iconClass: "icon-combos",
    icon: "fa-solid fa-box-open",
    image: "cardcombos.png",
    alt: "Decor Combos",
    title: "Decor Combos",
    description: "All-in-one decoration kits for easy setups",
    link: "/products?category=combos",
    btnClass: "link-combos",
  },
  {
    id: "manymore",
    cssClass: "card-manymore",
    iconClass: "icon-manymore",
    icon: "fa-solid fa-circle-plus",
    image: "cardmanymore.png",
    alt: "And More",
    title: "And More",
    description: "Discover many more decoration items",
    link: "/products?category=manymore",
    btnClass: "link-manymore",
  },
];
