/**
 * Occasion cards data — migrated exactly from index.html
 * 12 occasion cards with identical content, icons, links, and class names
 */
export const occasionCards = [
  {
    id: "birthday",
    slug: "birthday",
    cssClass: "card-birthday",
    iconClass: "icon-birthday",
    icon: "fa-solid fa-cake-candles",
    image: "Birthday.png",
    alt: "Birthday",
    title: "Birthday",
    description: "Make birthdays extra special & memorable",
    link: "/occasion/birthday",
    btnClass: "link-birthday",
  },
  {
    id: "anniversary",
    slug: "anniversary",
    cssClass: "card-anniversary",
    iconClass: "icon-anniversary",
    icon: "fa-solid fa-heart",
    image: "anniversary.png",
    alt: "Anniversary",
    title: "Anniversaries",
    description: "Celebrate love with elegant decorations",
    link: "/occasion/anniversary",
    btnClass: "link-anniversary",
  },
  {
    id: "annaprashan",
    slug: "annaprashan",
    cssClass: "card-annaprashan",
    iconClass: "icon-annaprashan",
    icon: "fa-solid fa-bowl-rice",
    image: "Annaprashan.png",
    alt: "Annaprashan",
    title: "Annaprashan",
    description: "Traditional decor for your little one's first meal",
    link: "/occasion/annaprashan",
    btnClass: "link-annaprashan",
  },
  {
    id: "baby-shower",
    slug: "baby-shower",
    cssClass: "card-babyshower",
    iconClass: "icon-babyshower",
    icon: "fa-solid fa-baby-carriage",
    image: "babyshower.png",
    alt: "Baby Shower",
    title: "Baby Shower",
    description: "Beautiful setups for the mom-to-be",
    link: "/occasion/baby-shower",
    btnClass: "link-babyshower",
  },
  {
    id: "welcome-baby",
    slug: "welcome-baby",
    cssClass: "card-welcomebaby",
    iconClass: "icon-welcomebaby",
    icon: "fa-solid fa-shoe-prints",
    image: "welcomebaby.png",
    alt: "Welcome Baby",
    title: "Welcome Baby",
    description: "Warm welcome for your new bundle of joy",
    link: "/occasion/welcome-baby",
    btnClass: "link-welcomebaby",
  },
  {
    id: "mehndi",
    slug: "mehndi",
    cssClass: "card-mehndi",
    iconClass: "icon-mehndi",
    icon: "fa-solid fa-hand",
    image: "mehndi.png",
    alt: "Mehndi",
    title: "Mehndi",
    description: "Vibrant themes for joyful mehndi events",
    link: "/occasion/mehndi",
    btnClass: "link-mehndi",
  },
  {
    id: "haldi",
    slug: "haldi",
    cssClass: "card-haldi",
    iconClass: "icon-haldi",
    icon: "fa-solid fa-mortar-pestle",
    image: "haldi.png",
    alt: "Haldi",
    title: "Haldi",
    description: "Bright and beautiful setups for haldi ceremonies",
    link: "/occasion/haldi",
    btnClass: "link-haldi",
  },
  {
    id: "krishna-janmashtami",
    slug: "krishna-janmashtami",
    cssClass: "card-krishna",
    iconClass: "icon-krishna",
    icon: "fa-solid fa-music",
    image: "krishna janmashtami.png",
    alt: "Krishna Janmashtami",
    title: "Krishna Janmashtami",
    description: "Celebrate the birth of Lord Krishna",
    link: "/occasion/krishna-janmashtami",
    btnClass: "link-krishna",
  },
  {
    id: "welcome-home",
    slug: "welcome-home",
    cssClass: "card-welcomehome",
    iconClass: "icon-welcomehome",
    icon: "fa-solid fa-house",
    image: "welcome home.png",
    alt: "Welcome Home",
    title: "Welcome Home",
    description: "Beautiful decorations to celebrate new beginnings",
    link: "/occasion/welcome-home",
    btnClass: "link-welcomehome",
  },
  {
    id: "bangle-ceremony",
    slug: "bangle-ceremony",
    cssClass: "card-bangle",
    iconClass: "icon-bangle",
    icon: "fa-solid fa-circle-dot",
    image: "bangle-ceremony.jpg",
    alt: "Bangle Ceremony",
    title: "Bangle Ceremony",
    description: "Colorful & traditional decor for a joyful bangle ceremony",
    link: "/products?category=bangle-ceremony",
    btnClass: "link-bangle",
  },
  {
    id: "independence-day",
    slug: "independence-day",
    cssClass: "card-independence",
    iconClass: "icon-independence",
    icon: "fa-solid fa-flag",
    image: "independence-day.jpg",
    alt: "Independence Day",
    title: "Independence Day",
    description: "Patriotic tricolor decorations to celebrate our nation",
    link: "/products?category=independence-day",
    btnClass: "link-independence",
  },
  {
    id: "many-more",
    slug: "many-more",
    cssClass: "card-manymore",
    iconClass: "icon-manymore-occ",
    icon: "fa-solid fa-gift",
    image: "manymore-occasions.png",
    alt: "Many More",
    title: "Many More",
    description: "Explore a wide range of decorations for every occasion",
    link: "/bestseller/many-more",
    btnClass: "link-manymore-occ",
  },
];
